catalogHost="catalog-service" 
cartHost="cart-service" 
currencyHost="currency-service" 
shippingHost="shipping-service" 
paymentHost="payment-service" 
emailHost="email-service"
cartTimeout=3.0
catalogTimeout=3.0
currencyTimeout=3.0
shippingTimeout=3.0
paymentTimeout=3.0
emailTimeout=3.0

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="localhost"
agentPort=4317
